export default {
  'adriana-behar': {
    'name': 'Adriana Behar',
    'fullName': 'Adriana Brandão Behar',
    'country': 'Bra',
    'sport': 'Beach Volleyball',
    'jobTitle': 'Retired Athlete',
    'birthDate': 'Feb. 14, 1969',
    'birthPlace': 'Rio de Janeiro, Brazil',
    'hometown': 'Fort Lauderdale, USA',
    'photo': 'Adriana_Behar.jpg',
  },
  'bernardinho': {
    'name': 'Bernardinho',
    'fullName': 'Bernardo Rezende',
    'country': 'Bra',
    'sport': 'Volleyball',
    'jobTitle': 'Coach / Athlete',
    'birthDate': 'Aug. 25, 1959',
    'birthPlace': 'Rio de Janeiro, Brazil',
    'hometown': 'Rio de Janeiro, Brazil',
    'photo': 'bernardinho.jpg',
  },
  'shelda-bede': {
    'name': 'Shelda',
    'fullName': 'Shelda Bedê',
    'country': 'Bra',
    'sport': 'Beach Volleyball',
    'jobTitle': 'Retired Athlete',
    'birthDate': 'Jan. 1, 1973',
    'birthPlace': 'Fortaleza, Brazil',
    'hometown': 'Fortaleza, Brazil',
    'photo': 'shelda-bede.jpg',
  },
}
